services:
  db:
    image: postgres:15-alpine
    container_name: movies_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: moviesxmovies/backend:latest
    container_name: movies_api
    restart: always
    pull_policy: always
    env_file:
      - .env
    ports:
      - "7996:7996"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static_data:/app/staticfiles
      - media_data:/app/media

  web:
    image: moviesxmovies/frontend:latest
    container_name: movies_frontend
    restart: always
    pull_policy: always
    volumes:
      - frontend_data:/app

  redis:
    image: redis:7-alpine
    container_name: movies_redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  worker:
    image: moviesxmovies/backend:latest
    restart: always
    pull_policy: always
    command: python manage.py rqworker default
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - static_data:/app/staticfiles
      - media_data:/app/media

volumes:
  postgres_data:
  static_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/www/moviesxmovies/static
  media_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/www/moviesxmovies/media
  frontend_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/www/moviesxmovies/app
