global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "django"
    static_configs:
      - targets: ["api:7996"]
    metrics_path: /metrics
    metric_relabel_configs:
      - source_labels: [handler]
        regex: "^/metrics$"
        action: drop

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
